name: Integration tests

on:
  push:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
          architecture: 'x64'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install module and its dependencies
        run: |
          uv venv
          uv pip install -r requirements.dev.txt -e . -c requirements.txt

      - name: Lint with flake8
        run: |
          uv run flake8 tests inmanta_plugins
          uv run pyupgrade --py312-plus $(find inmanta_plugins tests -type f -name '*.py')

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
          architecture: 'x64'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install module and its dependencies
        run: |
          uv venv
          uv pip install -r requirements.dev.txt -e . -c requirements.txt

      - name: Run tests
        run: |
          uv run pytest tests -vvv --log-cli-level debug
